#include "registrationpage.h"

#include <QMessageBox>


/*
                                                                   Table "public.users"
    Column     |           Type           | Collation | Nullable |             Default              | Storage  | Compression | Stats target | Description
---------------+--------------------------+-----------+----------+----------------------------------+----------+-------------+--------------+-------------
 id            | integer                  |           | not null | generated by default as identity | plain    |             |              |
 username      | character varying(64)    |           | not null |                                  | extended |             |              |
 password_hash | text                     |           | not null |                                  | extended |             |              |
 email         | character varying(320)   |           |          |                                  | extended |             |              |
 phone         | character varying(32)    |           |          |                                  | extended |             |              |
 status        | character varying(32)    |           |          | 'active'::character varying      | extended |             |              |
 created_at    | timestamp with time zone |           |          | now()                            | plain    |             |              |
 updated_at    | timestamp with time zone |           |          | now()                            | plain    |             |              |
*/

/*
                                                                Table "public.accounts"
   Column   |           Type           | Collation | Nullable |             Default              | Storage  | Compression | Stats target | Description
------------+--------------------------+-----------+----------+----------------------------------+----------+-------------+--------------+-------------
 id         | integer                  |           | not null | generated by default as identity | plain    |             |              |
 user_id    | integer                  |           | not null |                                  | plain    |             |              |
 iban       | character varying(34)    |           |          |                                  | extended |             |              |
 balance    | numeric(18,2)            |           |          | 0                                | main     |             |              |
 currency   | character(3)             |           | not null |                                  | extended |             |              |
 status     | character varying(32)    |           |          | 'active'::character varying      | extended |             |              |
 created_at | timestamp with time zone |           |          | now()                            | plain    |             |              |
 updated_at | timestamp with time zone |           |          | now()                            | plain    |             |              |
*/


RegistrationPage::RegistrationPage(QWidget *parent)
    : QWidget(parent)
    , ui(new Ui::RegistrationPage)
{
    ui->setupUi(this);
    // Apply validators
    ui->emailEdit->setValidator(new QRegularExpressionValidator(m_emailRegex, this));
    ui->phoneEdit->setValidator(new QRegularExpressionValidator(m_phoneRegex, this));
    ui->phoneEdit->setText("+375");
    setupConnections();
}

void RegistrationPage::setupConnections()
{
    connect(ui->backToLogin, &QPushButton::clicked, this,
    [this]{
        emit pr_login();
    });

    connect(ui->registerButton, &QPushButton::clicked,
            this, &RegistrationPage::onRegisterClicked);
}

void RegistrationPage::onRegistrationError(const QString &error)
{
    ui->statusLabel->setText(tr("❌ %1").arg(error));
    ui->statusLabel->setStyleSheet(
        "font-size: 14px; "
        "color: #ff6b6b; "
        "padding: 16px; "
        "background: transparent;"
    );
    ui->registerButton->setEnabled(true);
}

void RegistrationPage::onRegistrationSuccess()
{
    ui->statusLabel->setText(tr("> Регистрация прошла успешно <"));
    ui->statusLabel->setStyleSheet(
        "font-size: 14px; "
        "color: #51cf66; "
        "padding: 16px; "
        "background: transparent;"
    );
    ui->registerButton->setEnabled(false);
}

void RegistrationPage::onRegisterClicked()
{
    const QString username = ui->usernameEdit->text().trimmed();
    const QString email = ui->emailEdit->text().trimmed();
    const QString phone = ui->phoneEdit->text().trimmed();
    const QString password = ui->passwordEdit->text();
    const QString password2 = ui->passwordConfirmEdit->text();

    if (username.isEmpty() || password.isEmpty() || password2.isEmpty()) {
        QMessageBox::warning(this, tr("Ошибка"), tr("Заполните все поля"));
        return;
    }
    if (password != password2) {
        QMessageBox::warning(this, tr("Ошибка"), tr("Пароли не совпадают"));
        return;
    }
    if (!ui->emailEdit->hasAcceptableInput()) {
        QMessageBox::warning(this, tr("Ошибка"), tr("Некорректный email"));
        return;
    }
    if (!ui->phoneEdit->hasAcceptableInput()) {
        QMessageBox::warning(this, tr("Ошибка"), tr("Некорректный номер телефона"));
        return;
    }
    RegData regData;
    regData.username = username;
    regData.email = email;
    regData.phone = phone;
    regData.password = password;
    emit r_registration(regData);

    ui->statusLabel->setText(tr("> Отправка запроса... <"));
    ui->statusLabel->setStyleSheet(
        "font-size: 14px; "
        "color: #4facfe; "
        "padding: 16px; "
        "background: transparent;"
    );
    ui->registerButton->setEnabled(false);
}

