#include "registrationpage.h"

#include <QMessageBox>
#include <qstyle.h>

/*
                                                                   Table "public.users"
    Column     |           Type           | Collation | Nullable |             Default              | Storage  | Compression | Stats target | Description
---------------+--------------------------+-----------+----------+----------------------------------+----------+-------------+--------------+-------------
 id            | integer                  |           | not null | generated by default as identity | plain    |             |              |
 username      | character varying(64)    |           | not null |                                  | extended |             |              |
 password_hash | text                     |           | not null |                                  | extended |             |              |
 email         | character varying(320)   |           |          |                                  | extended |             |              |
 phone         | character varying(32)    |           |          |                                  | extended |             |              |
 status        | character varying(32)    |           |          | 'active'::character varying      | extended |             |              |
 created_at    | timestamp with time zone |           |          | now()                            | plain    |             |              |
 updated_at    | timestamp with time zone |           |          | now()                            | plain    |             |              |
*/

RegistrationPage::RegistrationPage(QWidget *parent)
    : QWidget(parent)
    , ui(new Ui::RegistrationPage)
{
    ui->setupUi(this);
    reset();
    setupConnections();
}

void RegistrationPage::reset()
{
    ui->usernameEdit->clear();
    ui->emailEdit->clear();
    ui->phoneEdit->clear();
    ui->passwordEdit->clear();
    ui->passwordConfirmEdit->clear();
    ui->statusLabel->clear();
    ui->statusLabel->setProperty("state", "empty");
    ui->statusLabel->style()->polish(ui->statusLabel);
    ui->emailEdit->setValidator(new QRegularExpressionValidator(m_emailRegex, this));
    ui->phoneEdit->setValidator(new QRegularExpressionValidator(m_phoneRegex, this));
    ui->phoneEdit->setText("+375");
    ui->registerButton->setEnabled(true);
}

void RegistrationPage::setupConnections()
{
    connect(ui->backToLogin, &QPushButton::clicked, this,
    [this]{
        emit pr_login();
    });

    connect(ui->registerButton, &QPushButton::clicked,
            this, &RegistrationPage::onRegisterClicked);
}

void RegistrationPage::onRegistrationError(const QString &error)
{
    ui->statusLabel->setText(tr("> Ошибка: %1 <").arg(error));
    ui->statusLabel->setProperty("state", "error");
    ui->statusLabel->style()->polish(ui->statusLabel);
    ui->registerButton->setEnabled(true);
}

void RegistrationPage::onRegistrationSuccess()
{
    ui->statusLabel->setText(tr("> Регистрация прошла успешно <"));
    ui->statusLabel->setProperty("state", "success");
    ui->statusLabel->style()->polish(ui->statusLabel);
    ui->registerButton->setEnabled(false);
}

void RegistrationPage::onRegisterClicked()
{
    const QString username = ui->usernameEdit->text().trimmed();
    const QString email = ui->emailEdit->text().trimmed();
    const QString phone = ui->phoneEdit->text().trimmed();
    const QString password = ui->passwordEdit->text();
    const QString password2 = ui->passwordConfirmEdit->text();

    if (username.isEmpty() || password.isEmpty() || password2.isEmpty())
    {
        QMessageBox::warning(this, tr("Ошибка"), tr("Заполните все поля"));
    }
    else if (password != password2)
    {
        QMessageBox::warning(this, tr("Ошибка"), tr("Пароли не совпадают"));
    }
    else if (!ui->emailEdit->hasAcceptableInput())
    {
        QMessageBox::warning(this, tr("Ошибка"), tr("Некорректный email"));
    }
    else if (!ui->phoneEdit->hasAcceptableInput())
    {
        QMessageBox::warning(this, tr("Ошибка"), tr("Некорректный номер телефона"));
    }
    else
    {
        RegData regData;
        regData.username = username;
        regData.email = email;
        regData.phone = phone;
        regData.password = password;
        emit r_registration(regData);

        ui->statusLabel->setText(tr("> Отправка запроса... <"));
        ui->statusLabel->setProperty("state", "loading");
        ui->statusLabel->style()->polish(ui->statusLabel);
        ui->registerButton->setEnabled(false);
    }
}

